# Generated by Django 3.1.8 on 2021-07-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=50)),
                ('definition', models.CharField(max_length=150)),
                ('collection', models.IntegerField(default=0)),
            ],
        ),
    ]
